"""BibTeX exporter.

Embeds a custom field ``scopus_indexed = {true|false}`` so the user can
visually distinguish Scopus-indexed references in the .bib output.
"""

from __future__ import annotations

from typing import List

from find_references_scopus.core.models import Paper
from find_references_scopus.exporters.base import Exporter, PaperSource


class BibTeXExporter(Exporter):
    format_name = "bibtex"
    file_extension = ".bib"

    def export(self, source: PaperSource) -> str:
        papers = self._flatten(source)
        lines: List[str] = [
            "% Generated by findref 2.0 (https://github.com/find-refs)",
            "% Format: BibTeX",
            "% All entries include the custom field `scopus_indexed`",
            "",
        ]
        for idx, p in enumerate(papers):
            lines.append(self._format_entry(p, idx))
        return "\n".join(lines)

    def _format_entry(self, p: Paper, idx: int) -> str:
        cite_key = p.citation_key(idx)
        fields: List[str] = []

        if p.authors:
            authors_str = " and ".join(p.authors)
            fields.append(f"  author       = {{{_escape(authors_str)}}},")
        if p.title:
            fields.append(f"  title        = {{{_escape(p.title)}}},")
        if p.journal:
            fields.append(f"  journal      = {{{_escape(p.journal)}}},")
        if p.year:
            fields.append(f"  year         = {{{p.year}}},")
        if p.month:
            fields.append(f"  month        = {{{p.month}}},")
        if p.volume:
            fields.append(f"  volume       = {{{p.volume}}},")
        if p.issue:
            fields.append(f"  number       = {{{p.issue}}},")
        if p.pages:
            fields.append(f"  pages        = {{{_escape(p.pages)}}},")
        if p.doi:
            fields.append(f"  doi          = {{{p.doi}}},")
        if p.publisher:
            fields.append(f"  publisher    = {{{_escape(p.publisher)}}},")
        if p.issn_electronic:
            fields.append(f"  issn         = {{{p.issn_electronic}}},")
        if p.url:
            fields.append(f"  url          = {{{p.url}}},")
        if p.abstract:
            # Truncate very long abstracts to avoid huge .bib files
            abstr = p.abstract
            if len(abstr) > 1500:
                abstr = abstr[:1500] + "..."
            fields.append(f"  abstract     = {{{_escape(abstr)}}},")
        if p.keywords:
            kw = ", ".join(p.keywords)
            fields.append(f"  keywords     = {{{_escape(kw)}}},")
        # Custom scopus flag — main feature requested
        fields.append(f"  scopus_indexed = {{{str(p.scopus_indexed).lower()}}},")
        if p.quartile:
            fields.append(f"  quartile     = {{{p.quartile}}},")

        # Remove trailing comma from last field
        if fields and fields[-1].endswith(","):
            fields[-1] = fields[-1][:-1]

        body = "\n".join(fields)
        return f"@article{{{cite_key},\n{body}\n}}\n"


# ---------------------------------------------------------------------- #
# Helpers
# ---------------------------------------------------------------------- #

def _escape(s: str) -> str:
    """Escape BibTeX special chars."""
    if not isinstance(s, str):
        return str(s)
    # Placeholder for backslash to avoid double-escape
    s = s.replace("\\", "\x00BACKSLASH\x00")
    for ch in ["{", "}", "&", "%", "$", "#", "_"]:
        s = s.replace(ch, "\\" + ch)
    s = s.replace("^", "\\^{}")
    s = s.replace("~", "\\~{}")
    s = s.replace("\x00BACKSLASH\x00", "\\textbackslash{}")
    return s
